version: "3.8"

services:
    app:
        build: ./docker/php
        volumes:
            - ./src:/work/web

    web:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/work/web
        depends_on:
            - app
